<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" >
<context>
    <name>MainWindow</name>
    <message>
        <source>403</source>
        <translation>No Tienes Permiso.</translation>
    </message>
    <message>
        <source>Forbidden: Access denied</source>
        <translation>Acceso denengado.</translation>
    </message>
    <!--campos producto-->
    <message>
    <source>accountancy_code_buy</source>
    <translation>accountancy_code_buy</translation>
    </message>
    <message>
    <source>accountancy_code_buy_export</source>
    <translation>accountancy_code_buy_export</translation>
    </message>
    <message>
    <source>accountancy_code_buy_intra</source>
    <translation>accountancy_code_buy_intra</translation>
    </message>
    <message>
    <source>accountancy_code_sell</source>
    <translation>accountancy_code_sell</translation>
    </message>
    <message>
    <source>accountancy_code_sell_export</source>
    <translation>accountancy_code_sell_export</translation>
    </message>
    <message>
    <source>accountancy_code_sell_intra</source>
    <translation>accountancy_code_sell_intra</translation>
    </message>
    <message>
    <source>array_languages</source>
    <translation>array_languages</translation>
    </message>
    <message>
    <source>array_options</source>
    <translation>array_options</translation>
    </message>
    <message>
    <source>barcode</source>
    <translation>barcode</translation>
    </message>
    <message>
    <source>barcode_type</source>
    <translation>barcode_type</translation>
    </message>
    <message>
    <source>barcode_type_code</source>
    <translation>barcode_type_code</translation>
    </message>
    <message>
    <source>barcode_type_coder</source>
    <translation>barcode_type_coder</translation>
    </message>
    <message>
    <source>barcode_type_label</source>
    <translation>barcode_type_label</translation>
    </message>
    <message>
    <source>barcodes_extra</source>
    <translation>barcodes_extra</translation>
    </message>
    <message>
    <source>canvas</source>
    <translation>canvas</translation>
    </message>
    <message>
    <source>cond_reglement</source>
    <translation>cond_reglement</translation>
    </message>
    <message>
    <source>cond_reglement_id</source>
    <translation>cond_reglement_id</translation>
    </message>
    <message>
    <source>contact</source>
    <translation>contact</translation>
    </message>
    <message>
    <source>contact_id</source>
    <translation>contact_id</translation>
    </message>
    <message>
    <source>cost_price</source>
    <translation>cost_price</translation>
    </message>
    <message>
    <source>country</source>
    <translation>country</translation>
    </message>
    <message>
    <source>country_code</source>
    <translation>country_code</translation>
    </message>
    <message>
    <source>country_id</source>
    <translation>country_id</translation>
    </message>
    <message>
    <source>customcode</source>
    <translation>customcode</translation>
    </message>
    <message>
    <source>date_creation</source>
    <translation>date_creation</translation>
    </message>
    <message>
    <source>date_modification</source>
    <translation>date_modification</translation>
    </message>
    <message>
    <source>date_validation</source>
    <translation>date_validation</translation>
    </message>
    <message>
    <source>default_vat_code</source>
    <translation>default_vat_code</translation>
    </message>
    <message>
    <source>description</source>
    <translation>description</translation>
    </message>
    <message>
    <source>desiredstock</source>
    <translation>desiredstock</translation>
    </message>
    <message>
    <source>duration</source>
    <translation>duration</translation>
    </message>
    <message>
    <source>duration_unit</source>
    <translation>duration_unit</translation>
    </message>
    <message>
    <source>duration_value</source>
    <translation>duration_value</translation>
    </message>
    <message>
    <source>entity</source>
    <translation>entity</translation>
    </message>
    <message>
    <source>finished</source>
    <translation>finished</translation>
    </message>
    <message>
    <source>fk_account</source>
    <translation>fk_account</translation>
    </message>
    <message>
    <source>fk_default_warehouse</source>
    <translation>fk_default_warehouse</translation>
    </message>
    <message>
    <source>fk_incoterms</source>
    <translation>fk_incoterms</translation>
    </message>
    <message>
    <source>fk_price_expression</source>
    <translation>fk_price_expression</translation>
    </message>
    <message>
    <source>fk_project</source>
    <translation>fk_project</translation>
    </message>
    <message>
    <source>fk_unit</source>
    <translation>fk_unit</translation>
    </message>
    <message>
    <source>fourn_price_base_type</source>
    <translation>fourn_price_base_type</translation>
    </message>
    <message>
    <source>fourn_pu</source>
    <translation>fourn_pu</translation>
    </message>
    <message>
    <source>fourn_socid</source>
    <translation>fourn_socid</translation>
    </message>
    <message>
    <source>height</source>
    <translation>height</translation>
    </message>
    <message>
    <source>height_units</source>
    <translation>height_units</translation>
    </message>
    <message>
    <source>id</source>
    <translation>id</translation>
    </message>
    <message>
    <source>imgHeight</source>
    <translation>imgHeight</translation>
    </message>
    <message>
    <source>imgWidth</source>
    <translation>imgWidth</translation>
    </message>
    <message>
    <source>import_key</source>
    <translation>import_key</translation>
    </message>
    <message>
    <source>label</source>
    <translation>label</translation>
    </message>
    <message>
    <source>label_incoterms</source>
    <translation>label_incoterms</translation>
    </message>
    <message>
    <source>last_main_doc</source>
    <translation>last_main_doc</translation>
    </message>
    <message>
    <source>length</source>
    <translation>length</translation>
    </message>
    <message>
    <source>length_units</source>
    <translation>length_units</translation>
    </message>
    <message>
    <source>lines</source>
    <translation>lines</translation>
    </message>
    <message>
    <source>linkedObjectsIds</source>
    <translation>linkedObjectsIds</translation>
    </message>
    <message>
    <source>localtax1_tx</source>
    <translation>localtax1_tx</translation>
    </message>
    <message>
    <source>localtax1_type</source>
    <translation>localtax1_type</translation>
    </message>
    <message>
    <source>localtax2_tx</source>
    <translation>localtax2_tx</translation>
    </message>
    <message>
    <source>localtax2_type</source>
    <translation>localtax2_type</translation>
    </message>
    <message>
    <source>location_incoterms</source>
    <translation>location_incoterms</translation>
    </message>
    <message>
    <source>mode_reglement_id</source>
    <translation>mode_reglement_id</translation>
    </message>
    <message>
    <source>modelpdf</source>
    <translation>modelpdf</translation>
    </message>
    <message>
    <source>multilangs</source>
    <translation>multilangs</translation>
    </message>
    <message>
    <source>multiprices</source>
    <translation>multiprices</translation>
    </message>
    <message>
    <source>multiprices_base_type</source>
    <translation>multiprices_base_type</translation>
    </message>
    <message>
    <source>multiprices_min</source>
    <translation>multiprices_min</translation>
    </message>
    <message>
    <source>multiprices_min_ttc</source>
    <translation>multiprices_min_ttc</translation>
    </message>
    <message>
    <source>multiprices_recuperableonly</source>
    <translation>multiprices_recuperableonly</translation>
    </message>
    <message>
    <source>multiprices_ttc</source>
    <translation>multiprices_ttc</translation>
    </message>
    <message>
    <source>multiprices_tva_tx</source>
    <translation>multiprices_tva_tx</translation>
    </message>
    <message>
    <source>nbphoto</source>
    <translation>nbphoto</translation>
    </message>
    <message>
    <source>net_measure</source>
    <translation>net_measure</translation>
    </message>
    <message>
    <source>net_measure_units</source>
    <translation>net_measure_units</translation>
    </message>
    <message>
    <source>note</source>
    <translation>note</translation>
    </message>
    <message>
    <source>note_private</source>
    <translation>note_private</translation>
    </message>
    <message>
    <source>note_public</source>
    <translation>note_public</translation>
    </message>
    <message>
    <source>origin</source>
    <translation>origin</translation>
    </message>
    <message>
    <source>origin_id</source>
    <translation>origin_id</translation>
    </message>
    <message>
    <source>other</source>
    <translation>other</translation>
    </message>
    <message>
    <source>pmp</source>
    <translation>pmp</translation>
    </message>
    <message>
    <source>price</source>
    <translation>price</translation>
    </message>
    <message>
    <source>price_autogen</source>
    <translation>price_autogen</translation>
    </message>
    <message>
    <source>price_base_type</source>
    <translation>price_base_type</translation>
    </message>
    <message>
    <source>price_min</source>
    <translation>price_min</translation>
    </message>
    <message>
    <source>price_min_ttc</source>
    <translation>price_min_ttc</translation>
    </message>
    <message>
    <source>price_ttc</source>
    <translation>price_ttc</translation>
    </message>
    <message>
    <source>prices_by_qty</source>
    <translation>prices_by_qty</translation>
    </message>
    <message>
    <source>prices_by_qty_list</source>
    <translation>prices_by_qty_list</translation>
    </message>
    <message>
    <source>product_fourn_id</source>
    <translation>product_fourn_id</translation>
    </message>
    <message>
    <source>ref</source>
    <translation>ref</translation>
    </message>
    <message>
    <source>ref_ext</source>
    <translation>ref_ext</translation>
    </message>
    <message>
    <source>ref_fourn</source>
    <translation>ref_fourn</translation>
    </message>
    <message>
    <source>ref_supplier</source>
    <translation>ref_supplier</translation>
    </message>
    <message>
    <source>seuil_stock_alerte</source>
    <translation>seuil_stock_alerte</translation>
    </message>
    <message>
    <source>shipping_method_id</source>
    <translation>shipping_method_id</translation>
    </message>
    <message>
    <source>state</source>
    <translation>state</translation>
    </message>
    <message>
    <source>state_code</source>
    <translation>state_code</translation>
    </message>
    <message>
    <source>state_id</source>
    <translation>state_id</translation>
    </message>
    <message>
    <source>status</source>
    <translation>status</translation>
    </message>
    <message>
    <source>status_batch</source>
    <translation>status_batch</translation>
    </message>
    <message>
    <source>status_buy</source>
    <translation>status_buy</translation>
    </message>
    <message>
    <source>statut</source>
    <translation>statut</translation>
    </message>
    <message>
    <source>stock_reel</source>
    <translation>stock_reel</translation>
    </message>
    <message>
    <source>stock_theorique</source>
    <translation>stock_theorique</translation>
    </message>
    <message>
    <source>stock_warehouse</source>
    <translation>stock_warehouse</translation>
    </message>
    <message>
    <source>surface</source>
    <translation>surface</translation>
    </message>
    <message>
    <source>surface_units</source>
    <translation>surface_units</translation>
    </message>
    <message>
    <source>thirdparty</source>
    <translation>thirdparty</translation>
    </message>
    <message>
    <source>total_ht</source>
    <translation>total_ht</translation>
    </message>
    <message>
    <source>total_localtax1</source>
    <translation>total_localtax1</translation>
    </message>
    <message>
    <source>total_localtax2</source>
    <translation>total_localtax2</translation>
    </message>
    <message>
    <source>total_ttc</source>
    <translation>total_ttc</translation>
    </message>
    <message>
    <source>total_tva</source>
    <translation>total_tva</translation>
    </message>
    <message>
    <source>tva_npr</source>
    <translation>tva_npr</translation>
    </message>
    <message>
    <source>tva_tx</source>
    <translation>tva_tx</translation>
    </message>
    <message>
    <source>type</source>
    <translation>type</translation>
    </message>
    <message>
    <source>url</source>
    <translation>url</translation>
    </message>
    <message>
    <source>user</source>
    <translation>user</translation>
    </message>
    <message>
    <source>volume</source>
    <translation>volume</translation>
    </message>
    <message>
    <source>volume_units</source>
    <translation>volume_units</translation>
    </message>
    <message>
    <source>weight</source>
    <translation>weight</translation>
    </message>
    <message>
    <source>weight_units</source>
    <translation>weight_units</translation>
    </message>
    <message>
    <source>width</source>
    <translation>width</translation>
    </message>
    <message>
    <source>width_units</source>
    <translation>width_units</translation>
    </message>
</context>
</TS>
